server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb+srv://ivanzub:It4WMVHM2yJiKSTB@cluster0.pbqeyxv.mongodb.net/ht_shopping_cart?retryWrites=true&w=majority&appName=Cluster0
  application:
    name: ht-shopping-cart

logging:
  level:
    org.springframework: DEBUG
  file:
    name: logs/shopping-cart.log
    max-size: 10MB
    max-history: 7
