# Test-specific configuration
spring:
  data:
    mongodb:
      uri: #DB uri

logging:
  level:
    org.springframework: DEBUG

resilience:
  initial-wait-ms: 500
  multiplier: 2.0
  max-attempts: 3
