server:
  port: 8080

spring:
  profiles:
    active: dev
application:
    name: ht-shopping-cart

logging:
  level:
    org.springframework: INFO
  file:
    name: logs/shopping-cart.log
    max-size: 10MB
    max-history: 7
  pattern:
    correlation: "[%X{traceId:-},%X{spanId:-}] "
